# Generated by Django 5.0.1 on 2024-03-03 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('move_type', models.JSONField(default=list)),
                ('is_fast', models.BooleanField(default=False)),
                ('power', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('energy_gain', models.IntegerField()),
                ('cooldown', models.IntegerField()),
                ('buff', models.CharField(default='0,0,0,0,0', max_length=100, validators=[django.core.validators.RegexValidator(message="Buffs must be in the format 'chance,atk_buff_self,def_buff_self,atk_buff_opponent,def_buff_opponent' with integers.", regex='^-?\\d+,-?\\d+,-?\\d+,-?\\d+,-?\\d+$')])),
                ('archetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PokedexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dex_number', models.IntegerField()),
                ('species_name', models.CharField(max_length=100)),
                ('species_id', models.CharField(max_length=100)),
                ('parent', models.CharField(blank=True, max_length=100, null=True)),
                ('evolutions', models.JSONField(blank=True, default=list)),
                ('types', models.JSONField(default=list)),
                ('base_stats', models.CharField(default='0,0,0', max_length=50, validators=[django.core.validators.RegexValidator(message="Stats must be in the format 'attack,defense,stamina' with integers.", regex='^\\d+,\\d+,\\d+$')])),
                ('tags', models.JSONField(blank=True, default=list)),
                ('fast_moves', models.JSONField(default=list)),
                ('charged_moves', models.JSONField(default=list)),
                ('buddy_distance', models.IntegerField()),
                ('third_move_cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
