# Generated by Django 5.0.1 on 2024-03-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='buff',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
